// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQsDSsnQS-d571Vww7I34cx0Kc1TM-0M0',
    appId: '1:486969180590:android:0cdf56e4d84ddf6da4083f',
    messagingSenderId: '486969180590',
    projectId: 'tiger-test-mynotes',
    storageBucket: 'tiger-test-mynotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSSnOQOGrnnUYw7TzL-DF7-a2UhhsOptM',
    appId: '1:486969180590:ios:fd16ee737bba8ed6a4083f',
    messagingSenderId: '486969180590',
    projectId: 'tiger-test-mynotes',
    storageBucket: 'tiger-test-mynotes.appspot.com',
    iosClientId: '486969180590-ri4b3oaa551tk11t9bs2omv0mj4fvm8r.apps.googleusercontent.com',
    iosBundleId: 'com.tiger.mynotes',
  );
}
